import = [
	#"~/.config/alacritty/catppuccin-latte.toml"
	#"~/.config/alacritty/catppuccin-frappe.toml"
	#"~/.config/alacritty/catppuccin-macchiato.toml"
	"~/.config/alacritty/catppuccin-mocha.toml"
]

#[shell]
#program = "tmux"

[window]
decorations = "None"
startup_mode = "Maximized"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Bold" }
size = 13

[cursor]
style = { shape = "Beam", blinking = "On" }
unfocused_hollow = false
