# variables
STATUS_BG=colour81
STATUS_FG=colour0
SEPARATOR="|"

# set default term to xterm
set -g default-terminal xterm-256color

# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.tmux.conf

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# enable mouse mode (tmux 2.1 and above)
set -g mouse on

# increase history size
set-option -g history-limit 5000

# statusbar
set -g status-position bottom
set -g status-justify left
set -g status-style "bg=$STATUS_BG fg=$STATUS_FG"
set -g status-right "$SEPARATOR #{pane_title} $SEPARATOR "                        # title
set -ag status-right "%H:%M $SEPARATOR "                                          # time
set -ag status-right "%d-%b-%y $SEPARATOR "                                       # date
set -ag status-right "#(cat /sys/class/power_supply/BAT0/capacity)% $SEPARATOR"   # battery percentage
set -g status-right-length 160
set -g status-left-length 20

# panes
set -g pane-active-border-style "bg=colour0 fg=colour81"
set -g pane-border-style "fg=colour17 bg=colour0"

# start with multiple panes
new
neww
splitw -h
