# https://taskfile.dev

version: '3'

vars:
  SWAY:
    - sway
    - swaync
  NIRI:
    - niri
    - mako
  COMMON:
    - alacritty
    - autostart
    - fuzzel
    - swaylock
    - wallpapers
    - waybar
    - wleave
  TOOLS:
    - bat
    - clangd
    - claude
    - direnv
    - fish
    - git
    - ideavim
    - nushell
    - nvim
    - psql
    - rustic
    - starship

tasks:
  default:
    desc: Install Sway, Niri and tools.
    deps:
      - common
      - niri
      - sway
      - tools

  tools:
    desc: Install only tools.
    cmds:
      - stow --verbose {{.TOOLS | join " "}}

  common:
    desc: Install common desktop configs.
    cmds:
      - stow --verbose {{.COMMON | join " "}}

  sway:
    desc: Install only Sway.
    cmds:
      - stow --verbose {{.SWAY | join " "}}
    deps:
      - common

  niri:
    desc: Install only Niri.
    cmds:
      - stow --verbose {{.NIRI | join " "}}
    deps:
      - common

  clean:
    desc: Remove all dotfiles.
    cmds:
      - stow --verbose --delete */
