# https://taskfile.dev

version: '3'

vars:
  DESKTOPS:
    - sway
    - niri
    - alacritty
    - wallpapers
    - noctalia
  TOOLS:
    - bat
    - clangd
    - claude
    - direnv
    - fish
    - git
    - ideavim
    - nushell
    - nvim
    - psql
    - rustic
    - starship

tasks:
  default:
    desc: Install all.
    deps:
      - tools
    cmds:
      - stow --verbose {{.DESKTOPS | join " "}}

  tools:
    desc: Install only tools.
    cmds:
      - stow --verbose {{.TOOLS | join " "}}

  clean:
    desc: Remove all dotfiles.
    cmds:
      - stow --verbose --delete */
