format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$python\
$nix_shell\
$cmd_duration\
$character
"""

palette = "catppuccin_mocha" 
add_newline = false

[python]
format = '[(\($virtualenv\) )]($style)'

[cmd_duration]
min_time = 1_000
show_notifications = false
min_time_to_notify = 30_000
format = 'took [$duration](bold yellow) '

[directory]
read_only = " "
truncation_length = 1
truncate_to_repo = false

[git_branch]
symbol = " "

[nix_shell]
symbol = ' '

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
