[backup]
exclude-if-present = [".nobackup"]
git-ignore = false
no-require-git = true

globs = [
    "!__pycache__",
    "!.venv",
    "!venv",
    "!node_modules",
    "!target",
    "!*.o",
    "!*.class",
    "!build",
    "!dist",
    "!out",
    "!.cache",
]

[forget]
prune = true
keep-daily = 2
keep-weekly = 3
keep-monthly = 5

