### Include this file in all Sway configurations.

# --- Cursor ------------------------------------------------------------
seat seat0 xcursor_theme Adwaita 24

# --- Navigation --------------------------------------------------------
set $mod Mod4
set $left h
set $down j
set $up k
set $right l

# --- AZERTY number row -------------------------------------------------
set $one ampersand
set $two eacute
set $three quotedbl
set $four apostrophe
set $five parenleft
set $six minus
set $seven egrave
set $eight underscore
set $nine ccedilla
set $ten agrave

# --- Applications ------------------------------------------------------
set $files nautilus -w
set $term alacritty

# --- Focus & Decorations -----------------------------------------------
focus_wrapping no
focus_follows_mouse no
gaps inner 5
default_border pixel 1

# --- Common includes ---------------------------------------------------
include ./input.conf
include ./keybinds.conf
include ./output.conf
